services:
  - type: web
    name: recursivai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd blog_backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BLOG_API_BASE_URL
        value: https://recursivai-api.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: PAPERS_DIR
        value: /var/data/papers
      - key: SAVE_INTERMEDIATES
        value: "False"  
    disk:
      name: recursivai-data
      mountPath: /var/data
      sizeGB: 1