name: Find Top Research Papers

on:
  schedule:
    # Run at 12:00 AM IST (6:30 AM UTC) every 3 days
    - cron: '30 6 */3 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  find-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Find top papers
        run: |
          curl -X POST "https://recursivai-api.onrender.com/posts/find_top_papers"
